Repository loopstudio/rails-api-boilerplate, pull requests merged in 2020-10, with the labels that each got.

#237 Fix RSpec/MultipleExpectations errors
  .rubocop_todo.yml
  spec/requests/api/v1/users/update_spec.rb
Labels: maintenance

#238 Fix RSpec/SubjectStub error
  .rubocop_todo.yml
  spec/rubocop/cop/migration/add_index_spec.rb
Labels: maintenance

#225 change password reset token error
  app/controllers/api/v1/passwords_controller.rb
  app/controllers/concerns/exception_handler.rb
  spec/requests/api/v1/passwords/edit_spec.rb
Labels: on hold

#240 Fix RSpec/MultipleMemoizedHelpers errors
  .rubocop_todo.yml
  spec/requests/api/v1/users/create_spec.rb
Labels: maintenance

#252 Update spec/requests/api/v1/passwords/update_spec.rb file
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  spec/requests/api/v1/passwords/update_spec.rb
Labels: dependencies, maintenance
